name: Deploy Plane App to EC2

on:
  pull_request:
    types: [closed]
    branches:
      - development  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g
        

        
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance host/IP
          username: ${{ secrets.EC2_USERNAME }}  # SSH username for EC2
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH private key for authentication
        
          script: |
            chmod 600 ~/.ssh/id_ed25519
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_ed25519 <<< "${{secrets.SSH_PASS_PHRASE }}"
            git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519"
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.12.2/bin
            cd /home/ubuntu/PLANE-UI/DEV/cs-plane-ui
            git pull origin development
            npm run build   
            sudo systemctl restart nginx  # Restart nginx server
            pm2 restart cs-plane-dev   # restart pm2


   







 